# Generated by Django 6.0 on 2026-02-05 19:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options_project_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
