# Generated by Django 6.0 on 2026-02-05 19:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_task_created_at_task_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
