# Generated by Django 6.0 on 2026-02-05 19:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
